"""Synchronize generated Markdown sections across project docs."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from odracir.time_utils import now_iso


START_MARKER = "<!-- ODRACIR_STATUS_START -->"
END_MARKER = "<!-- ODRACIR_STATUS_END -->"


def sync_project_docs(root: str | Path | None = None) -> list[Path]:
    project_root = find_project_root(root)
    version = read_project_version(project_root)
    synced_at = now_iso()

    targets = [
        (
            project_root / "README.md",
            build_english_status_block(version=version, synced_at=synced_at),
            "[Changelog](CHANGELOG.md)",
        ),
        (
            project_root / "README.zh-CN.md",
            build_chinese_status_block(version=version, synced_at=synced_at),
            "[版本记录](CHANGELOG.md)",
        ),
    ]

    changed: list[Path] = []
    for path, block, anchor in targets:
        original = path.read_text(encoding="utf-8")
        updated = replace_generated_block(original, block, anchor)
        if updated != original:
            path.write_text(updated, encoding="utf-8", newline="\n")
            changed.append(path)

    return changed


def find_project_root(root: str | Path | None = None) -> Path:
    start = Path(root).resolve() if root else Path.cwd().resolve()

    for candidate in (start, *start.parents):
        if (candidate / "pyproject.toml").exists() and (candidate / "README.md").exists():
            return candidate

    return Path(__file__).resolve().parents[2]


def read_project_version(project_root: Path) -> str:
    pyproject = (project_root / "pyproject.toml").read_text(encoding="utf-8")
    match = re.search(r'^version\s*=\s*"([^"]+)"', pyproject, flags=re.MULTILINE)
    if not match:
        return "unknown"
    return match.group(1)


def build_english_status_block(version: str, synced_at: str) -> str:
    return f"""\
{START_MARKER}
## Project Status

This block is generated by `odracir sync-docs`.

- Version: `{version}`
- Stage: modular research prototype with traceable retrieval and summary harness
- Current focus: reliable artifacts, evidence-backed search, and supervised DeepSeek summary runs
- Last synced: `{synced_at}`

Active commands:

- `odracir "message"`: chat with the current Odracir agent.
- `odracir scan <research-folder>`: create or update `odracir_index.json` for a research folder.
- `odracir scan <research-folder> --papers-dir <paper-folder>`: scan an existing custom paper folder.
- `odracir extract <research-folder>`: extract PDF text into `.odracir/texts/`.
- `odracir status <research-folder>`: report processing states, OCR needs, and failures.
- `odracir chunk <research-folder>`: create traceable chunks in `.odracir/chunks/`.
- `odracir search <research-folder> "<query>"`: search chunks with page-level citations.
- `odracir summarize <research-folder> --paper <paper-id>`: generate a cited summary through DeepSeek.
- `odracir sync-docs`: refresh generated documentation status blocks.

{END_MARKER}
"""


def build_chinese_status_block(version: str, synced_at: str) -> str:
    return f"""\
{START_MARKER}
## 项目状态

此区块由 `odracir sync-docs` 自动生成。

- 版本：`{version}`
- 阶段：带有可追溯检索和摘要 harness 的模块化科研原型
- 当前重点：可靠 artifact、带证据检索和受控的 DeepSeek 摘要运行
- 最近同步：`{synced_at}`

当前命令：

- `odracir "message"`：与当前 Odracir agent 对话。
- `odracir scan <research-folder>`：为研究文件夹创建或更新 `odracir_index.json`。
- `odracir scan <research-folder> --papers-dir <paper-folder>`：扫描已有的自定义论文文件夹。
- `odracir extract <research-folder>`：将 PDF 正文提取到 `.odracir/texts/`。
- `odracir status <research-folder>`：报告处理状态、OCR 需求和失败项。
- `odracir chunk <research-folder>`：在 `.odracir/chunks/` 中创建可追溯 chunk。
- `odracir search <research-folder> "<query>"`：检索 chunk 并返回页码级引用。
- `odracir summarize <research-folder> --paper <paper-id>`：通过 DeepSeek 生成带引用摘要。
- `odracir sync-docs`：刷新自动生成的文档状态区块。

{END_MARKER}
"""


def replace_generated_block(content: str, block: str, anchor: str) -> str:
    pattern = re.compile(
        rf"{re.escape(START_MARKER)}.*?{re.escape(END_MARKER)}\n?",
        flags=re.DOTALL,
    )
    if pattern.search(content):
        return pattern.sub(block, content)

    anchor_index = content.find(anchor)
    if anchor_index == -1:
        return f"{block}\n{content}"

    line_end = content.find("\n", anchor_index)
    if line_end == -1:
        return f"{content}\n\n{block}"

    return f"{content[: line_end + 1]}\n{block}\n{content[line_end + 1:]}"


def main() -> None:
    parser = argparse.ArgumentParser(description="Synchronize generated Odracir docs.")
    parser.add_argument("--root", default=None, help="Project root. Defaults to cwd lookup.")
    args = parser.parse_args()

    changed = sync_project_docs(args.root)
    if changed:
        print("Updated docs:")
        for path in changed:
            print(f"- {path}")
    else:
        print("Docs already up to date.")


if __name__ == "__main__":
    main()
